#ifndef CMAKE_CONFIG_H
#define CMAKE_CONFIG_H

#define SWAN_BUILD_TYPE "DEBUG"

#define SWAN_VERSION_MAJOR 0
#define SWAN_VERSION_MINOR 1
#define SWAN_VERSION_PATCH 0

#define SWAN_VERSION_STRING "0.1.0"

#endif
