name = "Monospace 12"

image_file = "Monospace_12.png"
glyph_width  = 7
glyph_height = 15

supported_chars = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"

tab_width = 4

