name                    = "Monospace 16"
image_file              = "Monospace_16.png"
image_bold_file         = "Monospace_Bold_16.png"
image_italics_file      = "Monospace_Italics_16.png"
image_bold_italics_file = "Monospace_Bold_Italics_16.png"
glyph_width             = 15
glyph_height            = 29
tab_width               = 4
